---
abstract: 'A framework for high performance message passing'
author:
  - 'Dana M. Diederich <dana@realms.org>'
build_requires:
  English: 0
  File::Spec: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Perl::Critic::Progressive: 0
  Test::PerlTidy: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Transit
requires:
  Data::Dumper: 0
  File::Slurp: 0
  Getopt::Std: 0
  HTTP::Lite: 0
  HTTP::Server::Simple::CGI: 0
  IPC::Msg: 0
  IPC::SysV: 0
  JSON: 0
  POE: 0
  POSIX: 0
  Storable: 0
  base: 0
  perl: 5.006
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dana/perl-IPC-Transit/issues
  homepage: https://github.com/dana/perl-IPC-Transit
  repository: https://github.com/dana/perl-IPC-Transit.git
version: 1.133280
